---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fileserver-configmap
data:
  nginx.conf: |
    pid       /var/run/nginx.pid;
    error_log /dev/stderr error;

    worker_processes auto;

    events {
      worker_connections  8192;
      use epoll;
    }

    http {
      default_type  text/html;
      server_tokens off;

      log_format main escape=default '$host - [$time_local] "$request" $status $bytes_sent "$http_referer" "$http_user_agent" $proxy_add_x_forwarded_for vcap_request_id:$upstream_http_x_vcap_request_id response_time:$upstream_response_time';

      access_log  /dev/stdout main;

      proxy_hide_header X-USER-GUID;  #user guid header should not be forwarded to client

      sendfile             on;  #enable use of sendfile()
      sendfile_max_chunk   1M;  #make sure not to block on fast clients reading large files
      tcp_nopush           on;
      tcp_nodelay          on;  #disable nagel's algorithm

      keepalive_timeout    75 20;

      limit_req_status 429;

      client_max_body_size 15M; #already enforced upstream but doesn't hurt.

      client_body_temp_path /tmp/client_body_temp;
      proxy_temp_path       /tmp/proxy_temp;

      # This block handles public endpoints over non-TLS secured HTTP
      # This is required for backwards compatibility during a rolling-deploy
      server {
        listen    8080;

        server_name  _;
        server_name_in_redirect off;

        proxy_send_timeout          900;
        proxy_read_timeout          900;

        root /fileserver;

        location / {
            try_files $uri $uri/;
        }
      }
    }
---
kind: Service
apiVersion: v1
metadata:
  name: file-server
  labels:
    app.kubernetes.io/name: file-server
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app.kubernetes.io/name: file-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-server
  labels:
    app.kubernetes.io/name: file-server
spec:
  # This is a singleton.
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: file-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: file-server
    spec:
      containers:
        - name: nginx
          image: ghcr.io/cloudfoundry/k8s/fileserver:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
      volumes:
        - name: nginx-config
          configMap:
            name: fileserver-configmap
---
