---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: forwarder-agent
  labels:
    app: forwarder-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: forwarder-agent
  template:
    metadata:
      labels:
        app: forwarder-agent
    spec:
      containers:
        - name: forwarder-agent
          image: ghcr.io/cloudfoundry/k8s/forwarder-agent:latest
          imagePullPolicy: Always
          env:
            - name: AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: AGENT_PORT
              value: "3458"
            - name: AGENT_CA_FILE_PATH
              value: /etc/ssl/certs/forwarder-agent/ca.crt
            - name: AGENT_CERT_FILE_PATH
              value: /etc/ssl/certs/forwarder-agent/tls.crt
            - name: AGENT_KEY_FILE_PATH
              value: /etc/ssl/certs/forwarder-agent/tls.key
            - name: METRICS_CA_FILE_PATH
              value: /etc/ssl/certs/forwarder-agent/ca.crt
            - name: METRICS_CERT_FILE_PATH
              value: /etc/ssl/certs/forwarder-agent/tls.crt
            - name: METRICS_KEY_FILE_PATH
              value: /etc/ssl/certs/forwarder-agent/tls.key
          volumeMounts:
            - name: cert
              mountPath: /etc/ssl/certs/forwarder-agent
      volumes:
        - name: tmp
          emptyDir: {}
        - name: cert
          secret:
            secretName: cert
---
kind: Service
apiVersion: v1
metadata:
  name: forwarder-agent
  labels:
    app: forwarder-agent
spec:
  ports:
    - port: 3458
      targetPort: 3458
      protocol: TCP
  selector:
    app: forwarder-agent
