// Code generated by counterfeiter. DO NOT EDIT.
package kubeletfakes

import (
	"sync"

	"code.cloudfoundry.org/executor"
	"code.cloudfoundry.org/k8s-garden-client/pkg/k8sgarden/kubelet"
	lager "code.cloudfoundry.org/lager/v3"
)

type FakeClient struct {
	GetMetricsStub        func(lager.Logger, []string) (map[string]executor.ContainerMetrics, error)
	getMetricsMutex       sync.RWMutex
	getMetricsArgsForCall []struct {
		arg1 lager.Logger
		arg2 []string
	}
	getMetricsReturns struct {
		result1 map[string]executor.ContainerMetrics
		result2 error
	}
	getMetricsReturnsOnCall map[int]struct {
		result1 map[string]executor.ContainerMetrics
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeClient) GetMetrics(arg1 lager.Logger, arg2 []string) (map[string]executor.ContainerMetrics, error) {
	var arg2Copy []string
	if arg2 != nil {
		arg2Copy = make([]string, len(arg2))
		copy(arg2Copy, arg2)
	}
	fake.getMetricsMutex.Lock()
	ret, specificReturn := fake.getMetricsReturnsOnCall[len(fake.getMetricsArgsForCall)]
	fake.getMetricsArgsForCall = append(fake.getMetricsArgsForCall, struct {
		arg1 lager.Logger
		arg2 []string
	}{arg1, arg2Copy})
	stub := fake.GetMetricsStub
	fakeReturns := fake.getMetricsReturns
	fake.recordInvocation("GetMetrics", []interface{}{arg1, arg2Copy})
	fake.getMetricsMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeClient) GetMetricsCallCount() int {
	fake.getMetricsMutex.RLock()
	defer fake.getMetricsMutex.RUnlock()
	return len(fake.getMetricsArgsForCall)
}

func (fake *FakeClient) GetMetricsCalls(stub func(lager.Logger, []string) (map[string]executor.ContainerMetrics, error)) {
	fake.getMetricsMutex.Lock()
	defer fake.getMetricsMutex.Unlock()
	fake.GetMetricsStub = stub
}

func (fake *FakeClient) GetMetricsArgsForCall(i int) (lager.Logger, []string) {
	fake.getMetricsMutex.RLock()
	defer fake.getMetricsMutex.RUnlock()
	argsForCall := fake.getMetricsArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeClient) GetMetricsReturns(result1 map[string]executor.ContainerMetrics, result2 error) {
	fake.getMetricsMutex.Lock()
	defer fake.getMetricsMutex.Unlock()
	fake.GetMetricsStub = nil
	fake.getMetricsReturns = struct {
		result1 map[string]executor.ContainerMetrics
		result2 error
	}{result1, result2}
}

func (fake *FakeClient) GetMetricsReturnsOnCall(i int, result1 map[string]executor.ContainerMetrics, result2 error) {
	fake.getMetricsMutex.Lock()
	defer fake.getMetricsMutex.Unlock()
	fake.GetMetricsStub = nil
	if fake.getMetricsReturnsOnCall == nil {
		fake.getMetricsReturnsOnCall = make(map[int]struct {
			result1 map[string]executor.ContainerMetrics
			result2 error
		})
	}
	fake.getMetricsReturnsOnCall[i] = struct {
		result1 map[string]executor.ContainerMetrics
		result2 error
	}{result1, result2}
}

func (fake *FakeClient) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeClient) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ kubelet.Client = new(FakeClient)
