// Code generated by counterfeiter. DO NOT EDIT.
package containerdfakes

import (
	"context"
	"sync"

	"github.com/containerd/containerd/v2/client"
	"github.com/containerd/containerd/v2/core/content"
	"github.com/containerd/containerd/v2/core/images"
	"github.com/containerd/platforms"
	digest "github.com/opencontainers/go-digest"
	v1 "github.com/opencontainers/image-spec/specs-go/v1"
)

type FakeImage struct {
	ConfigStub        func(context.Context) (v1.Descriptor, error)
	configMutex       sync.RWMutex
	configArgsForCall []struct {
		arg1 context.Context
	}
	configReturns struct {
		result1 v1.Descriptor
		result2 error
	}
	configReturnsOnCall map[int]struct {
		result1 v1.Descriptor
		result2 error
	}
	ContentStoreStub        func() content.Store
	contentStoreMutex       sync.RWMutex
	contentStoreArgsForCall []struct {
	}
	contentStoreReturns struct {
		result1 content.Store
	}
	contentStoreReturnsOnCall map[int]struct {
		result1 content.Store
	}
	IsUnpackedStub        func(context.Context, string) (bool, error)
	isUnpackedMutex       sync.RWMutex
	isUnpackedArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	isUnpackedReturns struct {
		result1 bool
		result2 error
	}
	isUnpackedReturnsOnCall map[int]struct {
		result1 bool
		result2 error
	}
	LabelsStub        func() map[string]string
	labelsMutex       sync.RWMutex
	labelsArgsForCall []struct {
	}
	labelsReturns struct {
		result1 map[string]string
	}
	labelsReturnsOnCall map[int]struct {
		result1 map[string]string
	}
	MetadataStub        func() images.Image
	metadataMutex       sync.RWMutex
	metadataArgsForCall []struct {
	}
	metadataReturns struct {
		result1 images.Image
	}
	metadataReturnsOnCall map[int]struct {
		result1 images.Image
	}
	NameStub        func() string
	nameMutex       sync.RWMutex
	nameArgsForCall []struct {
	}
	nameReturns struct {
		result1 string
	}
	nameReturnsOnCall map[int]struct {
		result1 string
	}
	PlatformStub        func() platforms.MatchComparer
	platformMutex       sync.RWMutex
	platformArgsForCall []struct {
	}
	platformReturns struct {
		result1 platforms.MatchComparer
	}
	platformReturnsOnCall map[int]struct {
		result1 platforms.MatchComparer
	}
	RootFSStub        func(context.Context) ([]digest.Digest, error)
	rootFSMutex       sync.RWMutex
	rootFSArgsForCall []struct {
		arg1 context.Context
	}
	rootFSReturns struct {
		result1 []digest.Digest
		result2 error
	}
	rootFSReturnsOnCall map[int]struct {
		result1 []digest.Digest
		result2 error
	}
	SizeStub        func(context.Context) (int64, error)
	sizeMutex       sync.RWMutex
	sizeArgsForCall []struct {
		arg1 context.Context
	}
	sizeReturns struct {
		result1 int64
		result2 error
	}
	sizeReturnsOnCall map[int]struct {
		result1 int64
		result2 error
	}
	SpecStub        func(context.Context) (v1.Image, error)
	specMutex       sync.RWMutex
	specArgsForCall []struct {
		arg1 context.Context
	}
	specReturns struct {
		result1 v1.Image
		result2 error
	}
	specReturnsOnCall map[int]struct {
		result1 v1.Image
		result2 error
	}
	TargetStub        func() v1.Descriptor
	targetMutex       sync.RWMutex
	targetArgsForCall []struct {
	}
	targetReturns struct {
		result1 v1.Descriptor
	}
	targetReturnsOnCall map[int]struct {
		result1 v1.Descriptor
	}
	UnpackStub        func(context.Context, string, ...client.UnpackOpt) error
	unpackMutex       sync.RWMutex
	unpackArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 []client.UnpackOpt
	}
	unpackReturns struct {
		result1 error
	}
	unpackReturnsOnCall map[int]struct {
		result1 error
	}
	UsageStub        func(context.Context, ...client.UsageOpt) (int64, error)
	usageMutex       sync.RWMutex
	usageArgsForCall []struct {
		arg1 context.Context
		arg2 []client.UsageOpt
	}
	usageReturns struct {
		result1 int64
		result2 error
	}
	usageReturnsOnCall map[int]struct {
		result1 int64
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeImage) Config(arg1 context.Context) (v1.Descriptor, error) {
	fake.configMutex.Lock()
	ret, specificReturn := fake.configReturnsOnCall[len(fake.configArgsForCall)]
	fake.configArgsForCall = append(fake.configArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.ConfigStub
	fakeReturns := fake.configReturns
	fake.recordInvocation("Config", []interface{}{arg1})
	fake.configMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeImage) ConfigCallCount() int {
	fake.configMutex.RLock()
	defer fake.configMutex.RUnlock()
	return len(fake.configArgsForCall)
}

func (fake *FakeImage) ConfigCalls(stub func(context.Context) (v1.Descriptor, error)) {
	fake.configMutex.Lock()
	defer fake.configMutex.Unlock()
	fake.ConfigStub = stub
}

func (fake *FakeImage) ConfigArgsForCall(i int) context.Context {
	fake.configMutex.RLock()
	defer fake.configMutex.RUnlock()
	argsForCall := fake.configArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeImage) ConfigReturns(result1 v1.Descriptor, result2 error) {
	fake.configMutex.Lock()
	defer fake.configMutex.Unlock()
	fake.ConfigStub = nil
	fake.configReturns = struct {
		result1 v1.Descriptor
		result2 error
	}{result1, result2}
}

func (fake *FakeImage) ConfigReturnsOnCall(i int, result1 v1.Descriptor, result2 error) {
	fake.configMutex.Lock()
	defer fake.configMutex.Unlock()
	fake.ConfigStub = nil
	if fake.configReturnsOnCall == nil {
		fake.configReturnsOnCall = make(map[int]struct {
			result1 v1.Descriptor
			result2 error
		})
	}
	fake.configReturnsOnCall[i] = struct {
		result1 v1.Descriptor
		result2 error
	}{result1, result2}
}

func (fake *FakeImage) ContentStore() content.Store {
	fake.contentStoreMutex.Lock()
	ret, specificReturn := fake.contentStoreReturnsOnCall[len(fake.contentStoreArgsForCall)]
	fake.contentStoreArgsForCall = append(fake.contentStoreArgsForCall, struct {
	}{})
	stub := fake.ContentStoreStub
	fakeReturns := fake.contentStoreReturns
	fake.recordInvocation("ContentStore", []interface{}{})
	fake.contentStoreMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeImage) ContentStoreCallCount() int {
	fake.contentStoreMutex.RLock()
	defer fake.contentStoreMutex.RUnlock()
	return len(fake.contentStoreArgsForCall)
}

func (fake *FakeImage) ContentStoreCalls(stub func() content.Store) {
	fake.contentStoreMutex.Lock()
	defer fake.contentStoreMutex.Unlock()
	fake.ContentStoreStub = stub
}

func (fake *FakeImage) ContentStoreReturns(result1 content.Store) {
	fake.contentStoreMutex.Lock()
	defer fake.contentStoreMutex.Unlock()
	fake.ContentStoreStub = nil
	fake.contentStoreReturns = struct {
		result1 content.Store
	}{result1}
}

func (fake *FakeImage) ContentStoreReturnsOnCall(i int, result1 content.Store) {
	fake.contentStoreMutex.Lock()
	defer fake.contentStoreMutex.Unlock()
	fake.ContentStoreStub = nil
	if fake.contentStoreReturnsOnCall == nil {
		fake.contentStoreReturnsOnCall = make(map[int]struct {
			result1 content.Store
		})
	}
	fake.contentStoreReturnsOnCall[i] = struct {
		result1 content.Store
	}{result1}
}

func (fake *FakeImage) IsUnpacked(arg1 context.Context, arg2 string) (bool, error) {
	fake.isUnpackedMutex.Lock()
	ret, specificReturn := fake.isUnpackedReturnsOnCall[len(fake.isUnpackedArgsForCall)]
	fake.isUnpackedArgsForCall = append(fake.isUnpackedArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.IsUnpackedStub
	fakeReturns := fake.isUnpackedReturns
	fake.recordInvocation("IsUnpacked", []interface{}{arg1, arg2})
	fake.isUnpackedMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeImage) IsUnpackedCallCount() int {
	fake.isUnpackedMutex.RLock()
	defer fake.isUnpackedMutex.RUnlock()
	return len(fake.isUnpackedArgsForCall)
}

func (fake *FakeImage) IsUnpackedCalls(stub func(context.Context, string) (bool, error)) {
	fake.isUnpackedMutex.Lock()
	defer fake.isUnpackedMutex.Unlock()
	fake.IsUnpackedStub = stub
}

func (fake *FakeImage) IsUnpackedArgsForCall(i int) (context.Context, string) {
	fake.isUnpackedMutex.RLock()
	defer fake.isUnpackedMutex.RUnlock()
	argsForCall := fake.isUnpackedArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeImage) IsUnpackedReturns(result1 bool, result2 error) {
	fake.isUnpackedMutex.Lock()
	defer fake.isUnpackedMutex.Unlock()
	fake.IsUnpackedStub = nil
	fake.isUnpackedReturns = struct {
		result1 bool
		result2 error
	}{result1, result2}
}

func (fake *FakeImage) IsUnpackedReturnsOnCall(i int, result1 bool, result2 error) {
	fake.isUnpackedMutex.Lock()
	defer fake.isUnpackedMutex.Unlock()
	fake.IsUnpackedStub = nil
	if fake.isUnpackedReturnsOnCall == nil {
		fake.isUnpackedReturnsOnCall = make(map[int]struct {
			result1 bool
			result2 error
		})
	}
	fake.isUnpackedReturnsOnCall[i] = struct {
		result1 bool
		result2 error
	}{result1, result2}
}

func (fake *FakeImage) Labels() map[string]string {
	fake.labelsMutex.Lock()
	ret, specificReturn := fake.labelsReturnsOnCall[len(fake.labelsArgsForCall)]
	fake.labelsArgsForCall = append(fake.labelsArgsForCall, struct {
	}{})
	stub := fake.LabelsStub
	fakeReturns := fake.labelsReturns
	fake.recordInvocation("Labels", []interface{}{})
	fake.labelsMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeImage) LabelsCallCount() int {
	fake.labelsMutex.RLock()
	defer fake.labelsMutex.RUnlock()
	return len(fake.labelsArgsForCall)
}

func (fake *FakeImage) LabelsCalls(stub func() map[string]string) {
	fake.labelsMutex.Lock()
	defer fake.labelsMutex.Unlock()
	fake.LabelsStub = stub
}

func (fake *FakeImage) LabelsReturns(result1 map[string]string) {
	fake.labelsMutex.Lock()
	defer fake.labelsMutex.Unlock()
	fake.LabelsStub = nil
	fake.labelsReturns = struct {
		result1 map[string]string
	}{result1}
}

func (fake *FakeImage) LabelsReturnsOnCall(i int, result1 map[string]string) {
	fake.labelsMutex.Lock()
	defer fake.labelsMutex.Unlock()
	fake.LabelsStub = nil
	if fake.labelsReturnsOnCall == nil {
		fake.labelsReturnsOnCall = make(map[int]struct {
			result1 map[string]string
		})
	}
	fake.labelsReturnsOnCall[i] = struct {
		result1 map[string]string
	}{result1}
}

func (fake *FakeImage) Metadata() images.Image {
	fake.metadataMutex.Lock()
	ret, specificReturn := fake.metadataReturnsOnCall[len(fake.metadataArgsForCall)]
	fake.metadataArgsForCall = append(fake.metadataArgsForCall, struct {
	}{})
	stub := fake.MetadataStub
	fakeReturns := fake.metadataReturns
	fake.recordInvocation("Metadata", []interface{}{})
	fake.metadataMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeImage) MetadataCallCount() int {
	fake.metadataMutex.RLock()
	defer fake.metadataMutex.RUnlock()
	return len(fake.metadataArgsForCall)
}

func (fake *FakeImage) MetadataCalls(stub func() images.Image) {
	fake.metadataMutex.Lock()
	defer fake.metadataMutex.Unlock()
	fake.MetadataStub = stub
}

func (fake *FakeImage) MetadataReturns(result1 images.Image) {
	fake.metadataMutex.Lock()
	defer fake.metadataMutex.Unlock()
	fake.MetadataStub = nil
	fake.metadataReturns = struct {
		result1 images.Image
	}{result1}
}

func (fake *FakeImage) MetadataReturnsOnCall(i int, result1 images.Image) {
	fake.metadataMutex.Lock()
	defer fake.metadataMutex.Unlock()
	fake.MetadataStub = nil
	if fake.metadataReturnsOnCall == nil {
		fake.metadataReturnsOnCall = make(map[int]struct {
			result1 images.Image
		})
	}
	fake.metadataReturnsOnCall[i] = struct {
		result1 images.Image
	}{result1}
}

func (fake *FakeImage) Name() string {
	fake.nameMutex.Lock()
	ret, specificReturn := fake.nameReturnsOnCall[len(fake.nameArgsForCall)]
	fake.nameArgsForCall = append(fake.nameArgsForCall, struct {
	}{})
	stub := fake.NameStub
	fakeReturns := fake.nameReturns
	fake.recordInvocation("Name", []interface{}{})
	fake.nameMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeImage) NameCallCount() int {
	fake.nameMutex.RLock()
	defer fake.nameMutex.RUnlock()
	return len(fake.nameArgsForCall)
}

func (fake *FakeImage) NameCalls(stub func() string) {
	fake.nameMutex.Lock()
	defer fake.nameMutex.Unlock()
	fake.NameStub = stub
}

func (fake *FakeImage) NameReturns(result1 string) {
	fake.nameMutex.Lock()
	defer fake.nameMutex.Unlock()
	fake.NameStub = nil
	fake.nameReturns = struct {
		result1 string
	}{result1}
}

func (fake *FakeImage) NameReturnsOnCall(i int, result1 string) {
	fake.nameMutex.Lock()
	defer fake.nameMutex.Unlock()
	fake.NameStub = nil
	if fake.nameReturnsOnCall == nil {
		fake.nameReturnsOnCall = make(map[int]struct {
			result1 string
		})
	}
	fake.nameReturnsOnCall[i] = struct {
		result1 string
	}{result1}
}

func (fake *FakeImage) Platform() platforms.MatchComparer {
	fake.platformMutex.Lock()
	ret, specificReturn := fake.platformReturnsOnCall[len(fake.platformArgsForCall)]
	fake.platformArgsForCall = append(fake.platformArgsForCall, struct {
	}{})
	stub := fake.PlatformStub
	fakeReturns := fake.platformReturns
	fake.recordInvocation("Platform", []interface{}{})
	fake.platformMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeImage) PlatformCallCount() int {
	fake.platformMutex.RLock()
	defer fake.platformMutex.RUnlock()
	return len(fake.platformArgsForCall)
}

func (fake *FakeImage) PlatformCalls(stub func() platforms.MatchComparer) {
	fake.platformMutex.Lock()
	defer fake.platformMutex.Unlock()
	fake.PlatformStub = stub
}

func (fake *FakeImage) PlatformReturns(result1 platforms.MatchComparer) {
	fake.platformMutex.Lock()
	defer fake.platformMutex.Unlock()
	fake.PlatformStub = nil
	fake.platformReturns = struct {
		result1 platforms.MatchComparer
	}{result1}
}

func (fake *FakeImage) PlatformReturnsOnCall(i int, result1 platforms.MatchComparer) {
	fake.platformMutex.Lock()
	defer fake.platformMutex.Unlock()
	fake.PlatformStub = nil
	if fake.platformReturnsOnCall == nil {
		fake.platformReturnsOnCall = make(map[int]struct {
			result1 platforms.MatchComparer
		})
	}
	fake.platformReturnsOnCall[i] = struct {
		result1 platforms.MatchComparer
	}{result1}
}

func (fake *FakeImage) RootFS(arg1 context.Context) ([]digest.Digest, error) {
	fake.rootFSMutex.Lock()
	ret, specificReturn := fake.rootFSReturnsOnCall[len(fake.rootFSArgsForCall)]
	fake.rootFSArgsForCall = append(fake.rootFSArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.RootFSStub
	fakeReturns := fake.rootFSReturns
	fake.recordInvocation("RootFS", []interface{}{arg1})
	fake.rootFSMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeImage) RootFSCallCount() int {
	fake.rootFSMutex.RLock()
	defer fake.rootFSMutex.RUnlock()
	return len(fake.rootFSArgsForCall)
}

func (fake *FakeImage) RootFSCalls(stub func(context.Context) ([]digest.Digest, error)) {
	fake.rootFSMutex.Lock()
	defer fake.rootFSMutex.Unlock()
	fake.RootFSStub = stub
}

func (fake *FakeImage) RootFSArgsForCall(i int) context.Context {
	fake.rootFSMutex.RLock()
	defer fake.rootFSMutex.RUnlock()
	argsForCall := fake.rootFSArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeImage) RootFSReturns(result1 []digest.Digest, result2 error) {
	fake.rootFSMutex.Lock()
	defer fake.rootFSMutex.Unlock()
	fake.RootFSStub = nil
	fake.rootFSReturns = struct {
		result1 []digest.Digest
		result2 error
	}{result1, result2}
}

func (fake *FakeImage) RootFSReturnsOnCall(i int, result1 []digest.Digest, result2 error) {
	fake.rootFSMutex.Lock()
	defer fake.rootFSMutex.Unlock()
	fake.RootFSStub = nil
	if fake.rootFSReturnsOnCall == nil {
		fake.rootFSReturnsOnCall = make(map[int]struct {
			result1 []digest.Digest
			result2 error
		})
	}
	fake.rootFSReturnsOnCall[i] = struct {
		result1 []digest.Digest
		result2 error
	}{result1, result2}
}

func (fake *FakeImage) Size(arg1 context.Context) (int64, error) {
	fake.sizeMutex.Lock()
	ret, specificReturn := fake.sizeReturnsOnCall[len(fake.sizeArgsForCall)]
	fake.sizeArgsForCall = append(fake.sizeArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.SizeStub
	fakeReturns := fake.sizeReturns
	fake.recordInvocation("Size", []interface{}{arg1})
	fake.sizeMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeImage) SizeCallCount() int {
	fake.sizeMutex.RLock()
	defer fake.sizeMutex.RUnlock()
	return len(fake.sizeArgsForCall)
}

func (fake *FakeImage) SizeCalls(stub func(context.Context) (int64, error)) {
	fake.sizeMutex.Lock()
	defer fake.sizeMutex.Unlock()
	fake.SizeStub = stub
}

func (fake *FakeImage) SizeArgsForCall(i int) context.Context {
	fake.sizeMutex.RLock()
	defer fake.sizeMutex.RUnlock()
	argsForCall := fake.sizeArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeImage) SizeReturns(result1 int64, result2 error) {
	fake.sizeMutex.Lock()
	defer fake.sizeMutex.Unlock()
	fake.SizeStub = nil
	fake.sizeReturns = struct {
		result1 int64
		result2 error
	}{result1, result2}
}

func (fake *FakeImage) SizeReturnsOnCall(i int, result1 int64, result2 error) {
	fake.sizeMutex.Lock()
	defer fake.sizeMutex.Unlock()
	fake.SizeStub = nil
	if fake.sizeReturnsOnCall == nil {
		fake.sizeReturnsOnCall = make(map[int]struct {
			result1 int64
			result2 error
		})
	}
	fake.sizeReturnsOnCall[i] = struct {
		result1 int64
		result2 error
	}{result1, result2}
}

func (fake *FakeImage) Spec(arg1 context.Context) (v1.Image, error) {
	fake.specMutex.Lock()
	ret, specificReturn := fake.specReturnsOnCall[len(fake.specArgsForCall)]
	fake.specArgsForCall = append(fake.specArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.SpecStub
	fakeReturns := fake.specReturns
	fake.recordInvocation("Spec", []interface{}{arg1})
	fake.specMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeImage) SpecCallCount() int {
	fake.specMutex.RLock()
	defer fake.specMutex.RUnlock()
	return len(fake.specArgsForCall)
}

func (fake *FakeImage) SpecCalls(stub func(context.Context) (v1.Image, error)) {
	fake.specMutex.Lock()
	defer fake.specMutex.Unlock()
	fake.SpecStub = stub
}

func (fake *FakeImage) SpecArgsForCall(i int) context.Context {
	fake.specMutex.RLock()
	defer fake.specMutex.RUnlock()
	argsForCall := fake.specArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeImage) SpecReturns(result1 v1.Image, result2 error) {
	fake.specMutex.Lock()
	defer fake.specMutex.Unlock()
	fake.SpecStub = nil
	fake.specReturns = struct {
		result1 v1.Image
		result2 error
	}{result1, result2}
}

func (fake *FakeImage) SpecReturnsOnCall(i int, result1 v1.Image, result2 error) {
	fake.specMutex.Lock()
	defer fake.specMutex.Unlock()
	fake.SpecStub = nil
	if fake.specReturnsOnCall == nil {
		fake.specReturnsOnCall = make(map[int]struct {
			result1 v1.Image
			result2 error
		})
	}
	fake.specReturnsOnCall[i] = struct {
		result1 v1.Image
		result2 error
	}{result1, result2}
}

func (fake *FakeImage) Target() v1.Descriptor {
	fake.targetMutex.Lock()
	ret, specificReturn := fake.targetReturnsOnCall[len(fake.targetArgsForCall)]
	fake.targetArgsForCall = append(fake.targetArgsForCall, struct {
	}{})
	stub := fake.TargetStub
	fakeReturns := fake.targetReturns
	fake.recordInvocation("Target", []interface{}{})
	fake.targetMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeImage) TargetCallCount() int {
	fake.targetMutex.RLock()
	defer fake.targetMutex.RUnlock()
	return len(fake.targetArgsForCall)
}

func (fake *FakeImage) TargetCalls(stub func() v1.Descriptor) {
	fake.targetMutex.Lock()
	defer fake.targetMutex.Unlock()
	fake.TargetStub = stub
}

func (fake *FakeImage) TargetReturns(result1 v1.Descriptor) {
	fake.targetMutex.Lock()
	defer fake.targetMutex.Unlock()
	fake.TargetStub = nil
	fake.targetReturns = struct {
		result1 v1.Descriptor
	}{result1}
}

func (fake *FakeImage) TargetReturnsOnCall(i int, result1 v1.Descriptor) {
	fake.targetMutex.Lock()
	defer fake.targetMutex.Unlock()
	fake.TargetStub = nil
	if fake.targetReturnsOnCall == nil {
		fake.targetReturnsOnCall = make(map[int]struct {
			result1 v1.Descriptor
		})
	}
	fake.targetReturnsOnCall[i] = struct {
		result1 v1.Descriptor
	}{result1}
}

func (fake *FakeImage) Unpack(arg1 context.Context, arg2 string, arg3 ...client.UnpackOpt) error {
	fake.unpackMutex.Lock()
	ret, specificReturn := fake.unpackReturnsOnCall[len(fake.unpackArgsForCall)]
	fake.unpackArgsForCall = append(fake.unpackArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 []client.UnpackOpt
	}{arg1, arg2, arg3})
	stub := fake.UnpackStub
	fakeReturns := fake.unpackReturns
	fake.recordInvocation("Unpack", []interface{}{arg1, arg2, arg3})
	fake.unpackMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3...)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeImage) UnpackCallCount() int {
	fake.unpackMutex.RLock()
	defer fake.unpackMutex.RUnlock()
	return len(fake.unpackArgsForCall)
}

func (fake *FakeImage) UnpackCalls(stub func(context.Context, string, ...client.UnpackOpt) error) {
	fake.unpackMutex.Lock()
	defer fake.unpackMutex.Unlock()
	fake.UnpackStub = stub
}

func (fake *FakeImage) UnpackArgsForCall(i int) (context.Context, string, []client.UnpackOpt) {
	fake.unpackMutex.RLock()
	defer fake.unpackMutex.RUnlock()
	argsForCall := fake.unpackArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeImage) UnpackReturns(result1 error) {
	fake.unpackMutex.Lock()
	defer fake.unpackMutex.Unlock()
	fake.UnpackStub = nil
	fake.unpackReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeImage) UnpackReturnsOnCall(i int, result1 error) {
	fake.unpackMutex.Lock()
	defer fake.unpackMutex.Unlock()
	fake.UnpackStub = nil
	if fake.unpackReturnsOnCall == nil {
		fake.unpackReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.unpackReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeImage) Usage(arg1 context.Context, arg2 ...client.UsageOpt) (int64, error) {
	fake.usageMutex.Lock()
	ret, specificReturn := fake.usageReturnsOnCall[len(fake.usageArgsForCall)]
	fake.usageArgsForCall = append(fake.usageArgsForCall, struct {
		arg1 context.Context
		arg2 []client.UsageOpt
	}{arg1, arg2})
	stub := fake.UsageStub
	fakeReturns := fake.usageReturns
	fake.recordInvocation("Usage", []interface{}{arg1, arg2})
	fake.usageMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2...)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeImage) UsageCallCount() int {
	fake.usageMutex.RLock()
	defer fake.usageMutex.RUnlock()
	return len(fake.usageArgsForCall)
}

func (fake *FakeImage) UsageCalls(stub func(context.Context, ...client.UsageOpt) (int64, error)) {
	fake.usageMutex.Lock()
	defer fake.usageMutex.Unlock()
	fake.UsageStub = stub
}

func (fake *FakeImage) UsageArgsForCall(i int) (context.Context, []client.UsageOpt) {
	fake.usageMutex.RLock()
	defer fake.usageMutex.RUnlock()
	argsForCall := fake.usageArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeImage) UsageReturns(result1 int64, result2 error) {
	fake.usageMutex.Lock()
	defer fake.usageMutex.Unlock()
	fake.UsageStub = nil
	fake.usageReturns = struct {
		result1 int64
		result2 error
	}{result1, result2}
}

func (fake *FakeImage) UsageReturnsOnCall(i int, result1 int64, result2 error) {
	fake.usageMutex.Lock()
	defer fake.usageMutex.Unlock()
	fake.UsageStub = nil
	if fake.usageReturnsOnCall == nil {
		fake.usageReturnsOnCall = make(map[int]struct {
			result1 int64
			result2 error
		})
	}
	fake.usageReturnsOnCall[i] = struct {
		result1 int64
		result2 error
	}{result1, result2}
}

func (fake *FakeImage) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeImage) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ client.Image = new(FakeImage)
