// Code generated by counterfeiter. DO NOT EDIT.
package containerdfakes

import (
	"context"
	"sync"

	"code.cloudfoundry.org/k8s-garden-client/pkg/containerd"
	"github.com/containerd/containerd/v2/client"
	v1 "k8s.io/api/core/v1"
)

type FakeClient struct {
	DeleteStub        func(context.Context, client.Image) error
	deleteMutex       sync.RWMutex
	deleteArgsForCall []struct {
		arg1 context.Context
		arg2 client.Image
	}
	deleteReturns struct {
		result1 error
	}
	deleteReturnsOnCall map[int]struct {
		result1 error
	}
	IsServingStub        func(context.Context) (bool, error)
	isServingMutex       sync.RWMutex
	isServingArgsForCall []struct {
		arg1 context.Context
	}
	isServingReturns struct {
		result1 bool
		result2 error
	}
	isServingReturnsOnCall map[int]struct {
		result1 bool
		result2 error
	}
	LoadContainersStub        func(context.Context, []v1.ContainerStatus) (map[string]containerd.RunningContainer, error)
	loadContainersMutex       sync.RWMutex
	loadContainersArgsForCall []struct {
		arg1 context.Context
		arg2 []v1.ContainerStatus
	}
	loadContainersReturns struct {
		result1 map[string]containerd.RunningContainer
		result2 error
	}
	loadContainersReturnsOnCall map[int]struct {
		result1 map[string]containerd.RunningContainer
		result2 error
	}
	PullStub        func(context.Context, string, string, string) (client.Image, int64, error)
	pullMutex       sync.RWMutex
	pullArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 string
	}
	pullReturns struct {
		result1 client.Image
		result2 int64
		result3 error
	}
	pullReturnsOnCall map[int]struct {
		result1 client.Image
		result2 int64
		result3 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeClient) Delete(arg1 context.Context, arg2 client.Image) error {
	fake.deleteMutex.Lock()
	ret, specificReturn := fake.deleteReturnsOnCall[len(fake.deleteArgsForCall)]
	fake.deleteArgsForCall = append(fake.deleteArgsForCall, struct {
		arg1 context.Context
		arg2 client.Image
	}{arg1, arg2})
	stub := fake.DeleteStub
	fakeReturns := fake.deleteReturns
	fake.recordInvocation("Delete", []interface{}{arg1, arg2})
	fake.deleteMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeClient) DeleteCallCount() int {
	fake.deleteMutex.RLock()
	defer fake.deleteMutex.RUnlock()
	return len(fake.deleteArgsForCall)
}

func (fake *FakeClient) DeleteCalls(stub func(context.Context, client.Image) error) {
	fake.deleteMutex.Lock()
	defer fake.deleteMutex.Unlock()
	fake.DeleteStub = stub
}

func (fake *FakeClient) DeleteArgsForCall(i int) (context.Context, client.Image) {
	fake.deleteMutex.RLock()
	defer fake.deleteMutex.RUnlock()
	argsForCall := fake.deleteArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeClient) DeleteReturns(result1 error) {
	fake.deleteMutex.Lock()
	defer fake.deleteMutex.Unlock()
	fake.DeleteStub = nil
	fake.deleteReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeClient) DeleteReturnsOnCall(i int, result1 error) {
	fake.deleteMutex.Lock()
	defer fake.deleteMutex.Unlock()
	fake.DeleteStub = nil
	if fake.deleteReturnsOnCall == nil {
		fake.deleteReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.deleteReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeClient) IsServing(arg1 context.Context) (bool, error) {
	fake.isServingMutex.Lock()
	ret, specificReturn := fake.isServingReturnsOnCall[len(fake.isServingArgsForCall)]
	fake.isServingArgsForCall = append(fake.isServingArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.IsServingStub
	fakeReturns := fake.isServingReturns
	fake.recordInvocation("IsServing", []interface{}{arg1})
	fake.isServingMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeClient) IsServingCallCount() int {
	fake.isServingMutex.RLock()
	defer fake.isServingMutex.RUnlock()
	return len(fake.isServingArgsForCall)
}

func (fake *FakeClient) IsServingCalls(stub func(context.Context) (bool, error)) {
	fake.isServingMutex.Lock()
	defer fake.isServingMutex.Unlock()
	fake.IsServingStub = stub
}

func (fake *FakeClient) IsServingArgsForCall(i int) context.Context {
	fake.isServingMutex.RLock()
	defer fake.isServingMutex.RUnlock()
	argsForCall := fake.isServingArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeClient) IsServingReturns(result1 bool, result2 error) {
	fake.isServingMutex.Lock()
	defer fake.isServingMutex.Unlock()
	fake.IsServingStub = nil
	fake.isServingReturns = struct {
		result1 bool
		result2 error
	}{result1, result2}
}

func (fake *FakeClient) IsServingReturnsOnCall(i int, result1 bool, result2 error) {
	fake.isServingMutex.Lock()
	defer fake.isServingMutex.Unlock()
	fake.IsServingStub = nil
	if fake.isServingReturnsOnCall == nil {
		fake.isServingReturnsOnCall = make(map[int]struct {
			result1 bool
			result2 error
		})
	}
	fake.isServingReturnsOnCall[i] = struct {
		result1 bool
		result2 error
	}{result1, result2}
}

func (fake *FakeClient) LoadContainers(arg1 context.Context, arg2 []v1.ContainerStatus) (map[string]containerd.RunningContainer, error) {
	var arg2Copy []v1.ContainerStatus
	if arg2 != nil {
		arg2Copy = make([]v1.ContainerStatus, len(arg2))
		copy(arg2Copy, arg2)
	}
	fake.loadContainersMutex.Lock()
	ret, specificReturn := fake.loadContainersReturnsOnCall[len(fake.loadContainersArgsForCall)]
	fake.loadContainersArgsForCall = append(fake.loadContainersArgsForCall, struct {
		arg1 context.Context
		arg2 []v1.ContainerStatus
	}{arg1, arg2Copy})
	stub := fake.LoadContainersStub
	fakeReturns := fake.loadContainersReturns
	fake.recordInvocation("LoadContainers", []interface{}{arg1, arg2Copy})
	fake.loadContainersMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeClient) LoadContainersCallCount() int {
	fake.loadContainersMutex.RLock()
	defer fake.loadContainersMutex.RUnlock()
	return len(fake.loadContainersArgsForCall)
}

func (fake *FakeClient) LoadContainersCalls(stub func(context.Context, []v1.ContainerStatus) (map[string]containerd.RunningContainer, error)) {
	fake.loadContainersMutex.Lock()
	defer fake.loadContainersMutex.Unlock()
	fake.LoadContainersStub = stub
}

func (fake *FakeClient) LoadContainersArgsForCall(i int) (context.Context, []v1.ContainerStatus) {
	fake.loadContainersMutex.RLock()
	defer fake.loadContainersMutex.RUnlock()
	argsForCall := fake.loadContainersArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeClient) LoadContainersReturns(result1 map[string]containerd.RunningContainer, result2 error) {
	fake.loadContainersMutex.Lock()
	defer fake.loadContainersMutex.Unlock()
	fake.LoadContainersStub = nil
	fake.loadContainersReturns = struct {
		result1 map[string]containerd.RunningContainer
		result2 error
	}{result1, result2}
}

func (fake *FakeClient) LoadContainersReturnsOnCall(i int, result1 map[string]containerd.RunningContainer, result2 error) {
	fake.loadContainersMutex.Lock()
	defer fake.loadContainersMutex.Unlock()
	fake.LoadContainersStub = nil
	if fake.loadContainersReturnsOnCall == nil {
		fake.loadContainersReturnsOnCall = make(map[int]struct {
			result1 map[string]containerd.RunningContainer
			result2 error
		})
	}
	fake.loadContainersReturnsOnCall[i] = struct {
		result1 map[string]containerd.RunningContainer
		result2 error
	}{result1, result2}
}

func (fake *FakeClient) Pull(arg1 context.Context, arg2 string, arg3 string, arg4 string) (client.Image, int64, error) {
	fake.pullMutex.Lock()
	ret, specificReturn := fake.pullReturnsOnCall[len(fake.pullArgsForCall)]
	fake.pullArgsForCall = append(fake.pullArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 string
	}{arg1, arg2, arg3, arg4})
	stub := fake.PullStub
	fakeReturns := fake.pullReturns
	fake.recordInvocation("Pull", []interface{}{arg1, arg2, arg3, arg4})
	fake.pullMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1, ret.result2, ret.result3
	}
	return fakeReturns.result1, fakeReturns.result2, fakeReturns.result3
}

func (fake *FakeClient) PullCallCount() int {
	fake.pullMutex.RLock()
	defer fake.pullMutex.RUnlock()
	return len(fake.pullArgsForCall)
}

func (fake *FakeClient) PullCalls(stub func(context.Context, string, string, string) (client.Image, int64, error)) {
	fake.pullMutex.Lock()
	defer fake.pullMutex.Unlock()
	fake.PullStub = stub
}

func (fake *FakeClient) PullArgsForCall(i int) (context.Context, string, string, string) {
	fake.pullMutex.RLock()
	defer fake.pullMutex.RUnlock()
	argsForCall := fake.pullArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *FakeClient) PullReturns(result1 client.Image, result2 int64, result3 error) {
	fake.pullMutex.Lock()
	defer fake.pullMutex.Unlock()
	fake.PullStub = nil
	fake.pullReturns = struct {
		result1 client.Image
		result2 int64
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeClient) PullReturnsOnCall(i int, result1 client.Image, result2 int64, result3 error) {
	fake.pullMutex.Lock()
	defer fake.pullMutex.Unlock()
	fake.PullStub = nil
	if fake.pullReturnsOnCall == nil {
		fake.pullReturnsOnCall = make(map[int]struct {
			result1 client.Image
			result2 int64
			result3 error
		})
	}
	fake.pullReturnsOnCall[i] = struct {
		result1 client.Image
		result2 int64
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeClient) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeClient) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ containerd.Client = new(FakeClient)
